Carrera:
    type: entity
    table: carrera
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codigocarrera:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: codigoCarrera
        nombrecarrera:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: nombreCarrera
    lifecycleCallbacks: {  }
