CursoCorequisito:
    type: entity
    table: curso_corequisito
    indexes:
        fk_curso_has_curso_curso4_idx:
            columns:
                - corequisito_id
        fk_curso_has_curso_curso3_idx:
            columns:
                - curso_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        curso:
            targetEntity: Curso
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                curso_id:
                    referencedColumnName: id
            orphanRemoval: false
        corequisito:
            targetEntity: Curso
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                corequisito_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
