Horario:
    type: entity
    table: horario
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dia:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
        horainicio:
            type: time
            nullable: false
            comment: ''
            column: horaInicio
        horafin:
            type: time
            nullable: false
            comment: ''
            column: horaFin
    lifecycleCallbacks: {  }
