HorarioGrupo:
    type: entity
    table: horario_grupo
    indexes:
        fk_horario_has_grupo_grupo1_idx:
            columns:
                - grupo_id
        fk_horario_has_grupo_horario1_idx:
            columns:
                - horario_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        grupo:
            targetEntity: Grupo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                grupo_id:
                    referencedColumnName: id
            orphanRemoval: false
        horario:
            targetEntity: Horario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                horario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
